{"_id":"a2163967-451e-3cd0-8b54-4aed0002eb2d","authorName":"Anthony","authorEmailEncrypted":"G6H7L4Xh+ynbJtRWKRKUqAZA7tXzot+x1HlgxsCcOMUFDVOLQL/CizRffU1rOO5+w9bMJKQMsqNqF/RkfRoDER2KIhaTeqjK7l5oIeNHqUpgNwKFPgIc21yhDZKDJg1my9BBfhijX8Nf0vrplHeZuIbKuTLVsbSFZj66fsZStbwcDLtCP5YQ85CCl4h7XOeiza8JvSHiHurjOBSPX0XqHrsuFiagWp15TAAQpzc5MrekPrDNml1d7GiDdopduPZteEHYrumkJQXt39R99wR/mS1NpnT6cuPn3za9A61aJlGx7QT+JWsxK9ERTbAZvV0XWxkj/t6MOOD7FQhKOMeT2eT8oa83NNvgr00llLRnMW4lmI1nMayEm+k5XlC8cJ1dB7t8qLp8BzSngWGuRFR7ILIQ2HH9kIV6tQ1gwpxQPsYXiKh4zkTvV4/3LP+XMNPCO0grdT+/ESpbK9rsc7SFqelnHjFSgaDZz1UjbVR45KuP3zVhQTppxMISuAvTZ9RuQAJd0FHtzZJanpWXA2iqqmJrIOerXbz1+CY5+0CtliBcGvShj32oLzqwTno2GehSog125rJs8wtGEG12STxQg6ZHt8+cLaOG9ot7G13IJbddAknyqpFuFQf4+9QWy6x+dKTCKUwjwhrgUXWZXvSs8lX2Gg6RyhZAlt0Nyq6nVjk=","authorEmailMD5":"46a5e710fa0a76871082bc7ed7b61c5f","message":"if i try catch inside of a task, then i have to use the dispatcher to display error dialog on ui thread","postId":"2014_04_announcement-msdn-async-mvvm-articles-b2165e1d-7e99-386d-b481-ed64583f3ab7","replyTo":"219201c9-57b9-3091-a4cf-af4aabfe7867","date":"2017-03-07T01:27:24Z","timestamp":1488850044,"authorUserId":"disqus:crosscourtac"}