{"_id":"a2163967-451e-3cd0-8b54-4aed0002eb2d","authorName":"Anthony","authorEmailEncrypted":"PxPKwt6kFW4R0DSZlVAAkEUHGvRNcZixVPDEe8MXEj3vEOi/HBqqv8RD+XOa5Y8Y6iuMmeRJqY/FIdcEjEdyu1wVmv/NtpQTxwwmGN0tXtk+EpZtaORRXIg1J+XD7LCnRCY2etQgBFbYY5s2UFzJUIwBTnBc2ZwzaJnhL1s9gsxhDr5sQAgJEjIkc6qKLBRE3RKc5GukhT6QYCgXwzVCCmsxW0odGs2vK/cTZAzvee26qFdleHVzeIdn47QSAAEaL2e5zcvtv2wpqPhcEkp837MwC2AOUIcS2D4GBLQLSeJdr4TKty3uyXsduSJDHUSUPVeZg2TlcTaw8cFIer86ks9/nJ2ZDJdVVnqvE6fnFI5yzXwPcfiknN4VDgAa0VfDYGRefUWeIfIBg9bEypgrb+K6QFgJRrO3wXr50QmgwDSy+7wXpKquzy+2rlDqSOHPe1cK6SVHiHLg5PRARwuexRbimBMAx6Br/B/RPWMtHSehvotgjQEDsCZ+XHRYHuLOSxi7k2YzxzWg+ijBevwcSMS+V0i32Jjxwm3yYiqM2LCSiCT4SXPb/pfsCKmbAmmMFAlKAu+OiNVoVSjhdXKhODAIdCEi0zoo4tVdRrhfLcluno0Ko1vkqFSzIi5zmx/9tqrM5jl0n4IMgXJukiJrl9L6HWwybvJn6z9EwQ/5gYw=","authorEmailMD5":"46a5e710fa0a76871082bc7ed7b61c5f","message":"if i try catch inside of a task, then i have to use the dispatcher to display error dialog on ui thread","postId":"2014_04_announcement-msdn-async-mvvm-articles-b2165e1d-7e99-386d-b481-ed64583f3ab7","replyTo":"219201c9-57b9-3091-a4cf-af4aabfe7867","date":"2017-03-07T01:27:24Z","timestamp":1488850044,"authorUserId":"disqus:crosscourtac"}