{"_id":"a2163967-451e-3cd0-8b54-4aed0002eb2d","authorName":"Anthony","authorEmailEncrypted":"UFPx8sy6cuyxDv55K9B39cndjBfzlT1JDtyYr0He85vbS/pUsJVP2531Mj66NoYuscndJVQ0f7991TMGMx+n7BcBY6tujovnXXeToKxxYWVr8+aCl9HRwbfu0K9NRZTf/N5NWTQZhpUQ6v/G7jsdOdBPN1n7XLTdHJs42N3lbwrPSr6uCxgj4c1HO9YqwUt0wogbYOsG5wMqdw1jBGFD0aPheKhOJeiVEOAYpXisUfh+ffudXFyt+S1r7MXXrjcgK/N+rBx7m9pNb/c/NPVh17B5hf0XhkwpTHbBuqwmZtx9LgHqA5TZ86SPTlqANrdHfBeiU2Ve1I9PVY8u0LUh/JA8eNtuDHun3RvtgU1H/tccAwBbWst7q/QyzVWkpFuZvsoIOFdxB6wOKSdJaROgi3HsVFDUPlOI6OunQHPpuc2jyVBu1T5abe5SJcv/iB9MEalwS9Le37r6dNwyxZxOi2bvW3En8E1kdxuiT6Y6NFG66SnWyj34p6ISy4drtnq6X0fK6bb3c9X9p9fvLwDXTWVdCROBJ2Z6EhzqgqN+PwsELq4QS7IdlKHi5n5QWh4Jk8+2anQIj69At6cYl+qSBM3R1HF6lAiGbOlf4M3WRKW9R7l3VgR+SjzwVGlGP6pph1EdM0NL/C1aUFKpriBK8wg0YNSUqNbKhrSeR1r56Mc=","authorEmailMD5":"46a5e710fa0a76871082bc7ed7b61c5f","authorUri":"","authorUserId":"disqus:crosscourtac","authorFallbackAvatar":"","message":"if i try catch inside of a task, then i have to use the dispatcher to display error dialog on ui thread","postId":"2014_04_announcement-msdn-async-mvvm-articles-b2165e1d-7e99-386d-b481-ed64583f3ab7","replyTo":"219201c9-57b9-3091-a4cf-af4aabfe7867","date":"2017-03-07T01:27:24Z","timestamp":1488850044}