{"_id":"2fbaf680-ff84-11eb-8a3c-cf8e5f9c2e1d","postId":"2013_09_taskrun-vs-backgroundworker-round-4-e33eb673-a094-3715-9282-0e28e7b5e733","postUri":"https://blog.stephencleary.com/2013/09/taskrun-vs-backgroundworker-round-4.html","replyTo":"1c743d30-fe2f-11eb-8029-d136489c6dab","authorEmailEncrypted":"djvk0GTcvhjIgLfq/zSrBbfydLv6+KVb6lR/Mbsuh68cKFELEmVuvQo4lKpTIGl90UB2jqb+cAgwkUWJBSYMR2UrMJ0VK4x57+ZzzSqFccgbFqJahwHPvPKTCv5a+atnsvWjDU3rPnW07B/4EsWOZ/3CH2U5NwW0KDk7kphspTstdTgB7ixOAPKPzBNrIpS4jDx6m+AuYE6hSplpBBufii2ygwloL4ORSeTZ67wWma2qlVex6nIA83WrmdoEb0YqFmCE5WB5mAtMAl6g3FFCRS37btpd9VG15lMjhjUyrKbugz4uD3t1GXa1e7gZFt2yqIIceSLojtbLXUTkY1wtcVNMd/RHgrk8A0lR4V8UKe9LDvGuaJ5H04ADDvBeUyoegwkBIdRdN/MH0V8I5jkujTHE413++zMAWPnBT/BebSO9MZm0Z7QX7sFDqQBrkTksYUDJfI0xC/XztRTrFGebNBOAB1y+TV9jTqQQfLyDkIvw5cvJqaOCK6SRktr3ZsizRr+bb7QHLyQ9GjDIanq3baXz5aM30y6BaRGftT2n199dh1TD4y1+/X82+oXOq69Rxdl8E86rqNM797v/Vg4tmiKdq0oTn4Za7qOoa1qCJBCUoHuWSqsRQzkZtxJgxmXtUixT7boYyUA/t9dgHdKuiRCHRSlpROmDKhI5Cnrvbr0=","authorEmailMD5":"f9a925838d5c9437e576f66658f167b7","authorName":"Serhiy Yaroshko","authorUri":"","message":"The question was about disposing of the _cts. Look: the button2_Click creates an instance of CancellationTokenSource, then tries to run a task and catches an OperationCanceledException - excellent, but when _cts will be disposed? Perhaps there should be *finally { _cts.Dispose(); }*?","date":"2021-08-17T17:54:36.894Z"}